21:29:09.295 [main] ERROR persistence.DBManager - Error en la base de datos
java.sql.SQLException: Table not found in statement [INSERT INTO usuario (nombre, usuario, clave) VALUES (?, ?, ?);]
	at org.hsqldb.jdbc.Util.throwError(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcConnection.prepareStatement(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.UsuarioDAOJdbcImpl.create(UsuarioDAOJdbcImpl.java:20) [bin/:?]
	at dao.UsuarioDAOJdbcImpl.create(UsuarioDAOJdbcImpl.java:1) [bin/:?]
	at test.TestDB.crear(TestDB.java:56) [bin/:?]
	at test.TestDB.main(TestDB.java:25) [bin/:?]
21:29:09.335 [main] ERROR persistence.DBManager - Error en la base de datos
java.sql.SQLException: Table not found in statement [INSERT INTO auto (dominio, duenio) VALUES (? ,? ); ]
	at org.hsqldb.jdbc.Util.throwError(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcConnection.prepareStatement(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.AutoDAOJdbcImpl.create(AutoDAOJdbcImpl.java:22) [bin/:?]
	at dao.AutoDAOJdbcImpl.create(AutoDAOJdbcImpl.java:1) [bin/:?]
	at test.TestDB.crear(TestDB.java:70) [bin/:?]
	at test.TestDB.main(TestDB.java:25) [bin/:?]
21:29:09.375 [main] ERROR persistence.DBManager - Error al intentar ejecutar la consulta en la base
java.sql.SQLException: Table not found in statement [SELECT id, nombre, usuario, clave FROM usuario]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.executeQuery(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.DAOJdbcImpl.executeQuery(DAOJdbcImpl.java:23) [bin/:?]
	at dao.UsuarioDAOJdbcImpl.read(UsuarioDAOJdbcImpl.java:42) [bin/:?]
	at test.TestDB.listar(TestDB.java:87) [bin/:?]
	at test.TestDB.main(TestDB.java:27) [bin/:?]
17:58:54.153 [main] ERROR persistence.DBManager - Table already exists: AUTO in statement [CREATE TABLE auto]
java.sql.SQLException: Table already exists: AUTO in statement [CREATE TABLE auto]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:16) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
17:58:54.319 [main] ERROR persistence.DBManager - Table already exists: AUTOPARTE in statement [CREATE TABLE autoparte]
java.sql.SQLException: Table already exists: AUTOPARTE in statement [CREATE TABLE autoparte]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:19) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
17:58:54.424 [main] ERROR persistence.DBManager - Table already exists: REPARACION in statement [CREATE TABLE reparacion]
java.sql.SQLException: Table already exists: REPARACION in statement [CREATE TABLE reparacion]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:22) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
17:58:54.536 [main] ERROR persistence.DBManager - Table already exists: REPARACION_AUTOPARTES in statement [CREATE TABLE reparacion_autopartes]
java.sql.SQLException: Table already exists: REPARACION_AUTOPARTES in statement [CREATE TABLE reparacion_autopartes]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:25) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
17:58:54.623 [main] ERROR persistence.DBManager - Table already exists: USUARIO in statement [CREATE TABLE usuario]
java.sql.SQLException: Table already exists: USUARIO in statement [CREATE TABLE usuario]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:28) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:07:10.507 [main] ERROR persistence.DBManager - Table already exists: AUTO in statement [CREATE TABLE auto]
java.sql.SQLException: Table already exists: AUTO in statement [CREATE TABLE auto]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:16) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:07:10.589 [main] ERROR persistence.DBManager - Table already exists: AUTOPARTE in statement [CREATE TABLE autoparte]
java.sql.SQLException: Table already exists: AUTOPARTE in statement [CREATE TABLE autoparte]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:19) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:07:10.636 [main] ERROR persistence.DBManager - Table already exists: REPARACION in statement [CREATE TABLE reparacion]
java.sql.SQLException: Table already exists: REPARACION in statement [CREATE TABLE reparacion]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:22) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:07:10.681 [main] ERROR persistence.DBManager - Table already exists: REPARACION_AUTOPARTES in statement [CREATE TABLE reparacion_autopartes]
java.sql.SQLException: Table already exists: REPARACION_AUTOPARTES in statement [CREATE TABLE reparacion_autopartes]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:25) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:07:10.732 [main] ERROR persistence.DBManager - Table already exists: USUARIO in statement [CREATE TABLE usuario]
java.sql.SQLException: Table already exists: USUARIO in statement [CREATE TABLE usuario]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.execute(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at persistence.DBCreate.execute(DBCreate.java:36) [bin/:?]
	at persistence.DBCreate.crearTablas(DBCreate.java:28) [bin/:?]
	at persistence.DBCreate.main(DBCreate.java:11) [bin/:?]
18:18:23.406 [main] ERROR persistence.DBManager - Error al intentar ejecutar la consulta en la base
java.sql.SQLException: Table not found in statement [SELECT id, nombre, usuario, clave FROM usuario]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.executeQuery(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.DAOJdbcImpl.executeQuery(DAOJdbcImpl.java:23) [bin/:?]
	at dao.UsuarioDAOJdbcImpl.read(UsuarioDAOJdbcImpl.java:47) [bin/:?]
	at test.TestDB.listar(TestDB.java:70) [bin/:?]
	at test.TestDB.main(TestDB.java:21) [bin/:?]
18:18:23.501 [main] ERROR persistence.DBManager - Error en la base de datos
java.sql.SQLException: Table not found in statement [INSERT INTO usuario (nombre, usuario, clave) VALUES (?, ?, ?);]
	at org.hsqldb.jdbc.Util.throwError(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcConnection.prepareStatement(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.UsuarioDAOJdbcImpl.create(UsuarioDAOJdbcImpl.java:24) [bin/:?]
	at dao.UsuarioDAOJdbcImpl.create(UsuarioDAOJdbcImpl.java:1) [bin/:?]
	at test.TestDB.crear(TestDB.java:39) [bin/:?]
	at test.TestDB.main(TestDB.java:22) [bin/:?]
18:18:23.505 [main] ERROR persistence.DBManager - Error en la base de datos
java.sql.SQLException: Table not found in statement [INSERT INTO auto (dominio, duenio) VALUES (? ,? ); ]
	at org.hsqldb.jdbc.Util.throwError(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcPreparedStatement.<init>(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcConnection.prepareStatement(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.AutoDAOJdbcImpl.create(AutoDAOJdbcImpl.java:24) [bin/:?]
	at dao.AutoDAOJdbcImpl.create(AutoDAOJdbcImpl.java:1) [bin/:?]
	at test.TestDB.crear(TestDB.java:53) [bin/:?]
	at test.TestDB.main(TestDB.java:22) [bin/:?]
18:18:23.506 [main] ERROR persistence.DBManager - Error al intentar ejecutar la consulta en la base
java.sql.SQLException: Table not found in statement [SELECT id, nombre, usuario, clave FROM usuario]
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.fetchResult(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at org.hsqldb.jdbc.jdbcStatement.executeQuery(Unknown Source) ~[hsqldb.jar:private-2008/06/01-10:22:29]
	at dao.DAOJdbcImpl.executeQuery(DAOJdbcImpl.java:23) [bin/:?]
	at dao.UsuarioDAOJdbcImpl.read(UsuarioDAOJdbcImpl.java:47) [bin/:?]
	at test.TestDB.listar(TestDB.java:70) [bin/:?]
	at test.TestDB.main(TestDB.java:23) [bin/:?]
